### ISSUE TITLE
NoMethodError "/fluentd-ui-0.4.2/lib/fluentd-ui.rb:27:in `data_dir'"

### ISSUE THREAD

**Issue by ebuildy** [fluent/fluentd-ui#197]
I am using the official Fluentd Docker image, then run 

```
RUN gem install -V fluentd-ui
```

When I start UI 

```
fluentd-ui start
```

```
fluentd_1     | /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-ui-0.4.2/lib/fluentd-ui.rb:27:in `data_dir': undefined method `+' for nil:NilClass (NoMethodError)
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-ui-0.4.2/app/models/user.rb:11:in `<class:User>'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-ui-0.4.2/app/models/user.rb:7:in `<top (required)>'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:457:in `load'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:457:in `block in load_file'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:647:in `new_constants_in'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:456:in `load_file'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:354:in `require_or_load'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:317:in `depend_on'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:233:in `require_dependency'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:471:in `each'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:471:in `block in eager_load!'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:469:in `each'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:469:in `eager_load!'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:346:in `eager_load!'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/finisher.rb:56:in `each'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/2.2.0/tsort.rb:345:in `each'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/2.2.0/tsort.rb:345:in `call'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-ui-0.4.2/config/environment.rb:5:in `<top (required)>'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-ui-0.4.2/config.ru:3:in `require'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-ui-0.4.2/config.ru:3:in `block in <main>'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-ui-0.4.2/config.ru:in `new'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-ui-0.4.2/config.ru:in `<main>'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
fluentd_1     |     from /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
fluentd_1     |     from /home/ubuntu/ruby/bin/rackup:23:in `load'
fluentd_1     |     from /home/ubuntu/ruby/bin/rackup:23:in `<main>'
```

**Comment by uu59** [comment]
It caused by `ENV["HOME"]` is nil because Dockerfile doesn't define that.
https://github.com/fluent/fluentd-docker-image/blob/master/Dockerfile

Can you define `HOME` or `FLUENTD_UI_DATA_DIR`  in your Dockerfile?

**Comment by uu59** [comment]
And note that fluentd-ui generates some config files.
If you want to be persistent them, please use mount volume.
https://docs.docker.com/userguide/dockervolumes/

**Comment by okkez** [comment]
Outdated.
