### ISSUE TITLE
LoadError: cannot load such file -- bigdecimal/util

### ISSUE THREAD

**Issue by rhtenhove** [fluent/fluentd-ui#214]
I'm trying to load this gem in the official fluent/fluentd Docker container. Running `fluentd-ui start` or `su-exec fluent fluentd-ui start` inside a container root shell causes the following error:

```
bundler: failed to load command: rackup (/usr/bin/rackup)
LoadError: cannot load such file -- bigdecimal/util
  /usr/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/big_decimal/conversions.rb:2:in `require'
  /usr/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/big_decimal/conversions.rb:2:in `<top (required)>'
  /usr/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/json.rb:4:in `require'
  /usr/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/json.rb:4:in `<top (required)>'
  /usr/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object.rb:12:in `require'
  /usr/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object.rb:12:in `<top (required)>'
  /usr/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/configuration.rb:2:in `require'
  /usr/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/configuration.rb:2:in `<top (required)>'
  /usr/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:2:in `require'
  /usr/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:2:in `<top (required)>'
  /usr/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:1:in `require'
  /usr/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:1:in `<top (required)>'
  /usr/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:7:in `require'
  /usr/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:7:in `<top (required)>'
  /usr/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails.rb:11:in `require'
  /usr/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails.rb:11:in `<top (required)>'
  /usr/lib/ruby/gems/2.3.0/gems/activemodel-4.2.8/lib/active_model/railtie.rb:2:in `require'
  /usr/lib/ruby/gems/2.3.0/gems/activemodel-4.2.8/lib/active_model/railtie.rb:2:in `<top (required)>'
  /usr/lib/ruby/gems/2.3.0/gems/fluentd-ui-0.4.4/config/application.rb:4:in `require'
  /usr/lib/ruby/gems/2.3.0/gems/fluentd-ui-0.4.4/config/application.rb:4:in `<top (required)>'
  /usr/lib/ruby/gems/2.3.0/gems/fluentd-ui-0.4.4/config/environment.rb:2:in `require'
  /usr/lib/ruby/gems/2.3.0/gems/fluentd-ui-0.4.4/config/environment.rb:2:in `<top (required)>'
  /usr/lib/ruby/gems/2.3.0/gems/fluentd-ui-0.4.4/config.ru:3:in `require'
  /usr/lib/ruby/gems/2.3.0/gems/fluentd-ui-0.4.4/config.ru:3:in `block in <main>'
  /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
  /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
  /usr/lib/ruby/gems/2.3.0/gems/fluentd-ui-0.4.4/config.ru:in `new'
  /usr/lib/ruby/gems/2.3.0/gems/fluentd-ui-0.4.4/config.ru:in `<main>'
  /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/builder.rb:49:in `eval'
  /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/builder.rb:49:in `new_from_string'
  /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/builder.rb:40:in `parse_file'
  /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/server.rb:300:in `build_app_and_options_from_config'
  /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/server.rb:209:in `app'
  /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/server.rb:337:in `wrapped_app'
  /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/server.rb:273:in `start'
  /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.8/lib/rack/server.rb:148:in `start'
  /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.8/bin/rackup:4:in `<top (required)>'
  /usr/bin/rackup:22:in `load'
  /usr/bin/rackup:22:in `<top (required)>'
```

This is after having installed both the `io-console` and `bigdecimal` gems. Both were required to fix other dependency errors.
The Dockerfile is as follows:
```
FROM fluent/fluentd
RUN apk --update --no-cache add build-base ruby-dev zlib-dev && \
gem install fluent-plugin-influxdb \
fluentd-ui io-console bigdecimal && \
gem sources --clear-all && \
apk del build-base ruby-dev zlib-dev
```

Since bigdecimal is installed, and running it as either the root or the fluent user, I'm at a loss on how to fix this issue.
Who knows what might be wrong?

**Comment by okkez** [comment]
fluentd-ui uses Gemfile to restrict installed gems.
Therefore you should use your own Gemfile to run fluentd-ui.
Maybe you can use `BUNDLE_GEMFILE` environment variable for this purpose.

**Comment by okkez** [comment]
No response. Closing.
If you face to the same issue, feel free to open new issue.
