### ISSUE TITLE
Getting error starting Fluentd-ui 

### ISSUE THREAD

**Issue by rajan471** [fluent/fluentd-ui#236]
Here is the error that I get:

```
root@Rajan:/home/rajan/Documents/fluentd-ui# fluentd-ui start
bundler: failed to load command: rackup (/usr/local/bin/rackup)
NameError: uninitialized constant Tilt::ErubiTemplate
  /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant'
  /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
  /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `rescue in load_missing_constant'
  /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
  /var/lib/gems/2.3.0/gems/haml-5.0.4/lib/haml/helpers/safe_erubi_template.rb:13:in `<module:Haml>'
  /var/lib/gems/2.3.0/gems/haml-5.0.4/lib/haml/helpers/safe_erubi_template.rb:4:in `<main>'
  /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
  /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
  /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
  /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
  /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
  /var/lib/gems/2.3.0/gems/haml-5.0.4/lib/haml/railtie.rb:38:in `block (2 levels) in <class:Railtie>'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:51:in `each'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
  /var/lib/gems/2.3.0/gems/actionview-5.2.0/lib/action_view/base.rb:213:in `<class:Base>'
  /var/lib/gems/2.3.0/gems/actionview-5.2.0/lib/action_view/base.rb:141:in `<module:ActionView>'
  /var/lib/gems/2.3.0/gems/actionview-5.2.0/lib/action_view/base.rb:12:in `<main>'
  /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
  /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
  /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
  /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
  /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
  /var/lib/gems/2.3.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:7:in `<main>'
  /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
  /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
  /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
  /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
  /var/lib/gems/2.3.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
  /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/application/default_middleware_stack.rb:49:in `block in build_stack'
  /var/lib/gems/2.3.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/stack.rb:47:in `initialize'
  /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/application/default_middleware_stack.rb:15:in `new'
  /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/application/default_middleware_stack.rb:15:in `build_stack'
  /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/application.rb:576:in `default_middleware_stack'
  /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/engine.rb:508:in `block in app'
  /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/engine.rb:506:in `synchronize'
  /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/engine.rb:506:in `app'
  /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
  /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
  /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
  /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
  /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
  /var/lib/gems/2.3.0/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
  /var/lib/gems/2.3.0/gems/fluentd-ui-1.0.0.alpha.2/config/environment.rb:5:in `<top (required)>'
  /var/lib/gems/2.3.0/gems/fluentd-ui-1.0.0.alpha.2/config.ru:3:in `require'
  /var/lib/gems/2.3.0/gems/fluentd-ui-1.0.0.alpha.2/config.ru:3:in `block in <main>'
  /var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
  /var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
  /var/lib/gems/2.3.0/gems/fluentd-ui-1.0.0.alpha.2/config.ru:in `new'
  /var/lib/gems/2.3.0/gems/fluentd-ui-1.0.0.alpha.2/config.ru:in `<main>'
  /var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
  /var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
  /var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
  /var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/server.rb:319:in `build_app_and_options_from_config'
  /var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
  /var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/server.rb:354:in `wrapped_app'
  /var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/server.rb:283:in `start'
  /var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/server.rb:148:in `start'
  /var/lib/gems/2.3.0/gems/rack-2.0.5/bin/rackup:4:in `<top (required)>'
  /usr/local/bin/rackup:23:in `load'
  /usr/local/bin/rackup:23:in `<top (required)>'
```

**Comment by okkez** [comment]
Maybe, you must run `fluentd-ui setup` first.

**Comment by smallsong** [comment]
Me too

**Comment by rajan471** [comment]
Worked. Thanks
