### ISSUE TITLE
Permission error: Gemfile.production.lock

### ISSUE THREAD

**Issue by gaui** [fluent/fluentd-ui#272]
When I try to run my custom Docker image (derived from `fluent/fluentd:v1.2.6-debian`), I get the following error:

```
[root@fogliano fluentd]# docker run my-fluentd:1.2.6
Bundler::PermissionError: There was an error while trying to write to `/var/lib/gems/2.3.0/gems/fluentd-ui-1.1.0/Gemfile.production.lock`. It is likely that you need to grant write permissions for that path.
  /var/lib/gems/2.3.0/gems/bundler-1.16.6/lib/bundler/shared_helpers.rb:120:in `rescue in filesystem_access'
  /var/lib/gems/2.3.0/gems/bundler-1.16.6/lib/bundler/shared_helpers.rb:118:in `filesystem_access'
  /var/lib/gems/2.3.0/gems/bundler-1.16.6/lib/bundler/definition.rb:354:in `lock'
  /var/lib/gems/2.3.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:121:in `lock'
  /var/lib/gems/2.3.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:48:in `setup'
  /var/lib/gems/2.3.0/gems/bundler-1.16.6/lib/bundler.rb:107:in `setup'
  /var/lib/gems/2.3.0/gems/bundler-1.16.6/lib/bundler/setup.rb:20:in `<top (required)>'
  /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
bundler: failed to load command: rackup (/usr/local/bin/rackup)
[root@fogliano fluentd]#
```

Here's my Dockerfile:

```
FROM fluent/fluentd:v1.2.6-debian

RUN apt-get update && apt-get install -y \
  build-essential \
  libcurl4-gnutls-dev \
  ruby-dev \
  libssl-dev \
  zlib1g-dev \
  libxml2-dev \
  libxslt1-dev

RUN gem install fluent-plugin-elasticsearch:2.11.11
RUN gem install fluent-plugin-kafka:0.7.9
RUN gem install fluent-plugin-slack:0.6.7
RUN gem install fluentd-ui

EXPOSE 8888 24224 9292

CMD exec fluentd-ui start
```

Any idea?

**Comment by gaui** [comment]
Thank you @okkez
