### ISSUE TITLE
unable to start fluentd-ui

### ISSUE THREAD

**Issue by TheWilhelm** [fluent/fluentd-ui#351]
greetings i have trouble to starting a fresh install.
i get the following output:
```
C:\Users\Username>fluentd-ui start --daemonize
E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activesupport-5.2.5/lib/active_support/core_ext/module/delegation.rb:156:in `delegate': Delegation needs a target. Supply an options hash with a :to key as the last argument (e.g. delegate :hello, to: :greeter). (ArgumentError)
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/draper-3.1.0/lib/draper/delegation.rb:10:in `delegate'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activemodel-5.2.5/lib/active_model/naming.rb:222:in `extended'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activemodel-5.2.5/lib/active_model/serializers/json.rb:13:in `extend'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activemodel-5.2.5/lib/active_model/serializers/json.rb:13:in `block in <module:JSON>'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activesupport-5.2.5/lib/active_support/concern.rb:122:in `class_eval'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activesupport-5.2.5/lib/active_support/concern.rb:122:in `append_features'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/draper-3.1.0/lib/draper/decorator.rb:10:in `include'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/draper-3.1.0/lib/draper/decorator.rb:10:in `<class:Decorator>'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/draper-3.1.0/lib/draper/decorator.rb:4:in `<module:Draper>'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/draper-3.1.0/lib/draper/decorator.rb:3:in `<main>'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/draper-3.1.0/lib/draper.rb:18:in `<main>'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fluentd-ui-1.2.1/config/application.rb:21:in `<top (required)>'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fluentd-ui-1.2.1/config/environment.rb:2:in `require_relative'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fluentd-ui-1.2.1/config/environment.rb:2:in `<top (required)>'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fluentd-ui-1.2.1/config.ru:3:in `require'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fluentd-ui-1.2.1/config.ru:3:in `block in <main>'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:168:in `start'
        from E:/unixland/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rack-2.2.3/bin/rackup:5:in `<top (required)>'
        from E:/unixland/Ruby30-x64/bin/rackup:23:in `load'
        from E:/unixland/Ruby30-x64/bin/rackup:23:in `<main>'
```

the Environment is a windows server 2016 version 1607

and ruby --version returns:
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x64-mingw32]

**Comment by kenhys** [comment]
As a workaround, you can use it with ruby 2.7.

**Comment by TheWilhelm** [comment]
yes the using 2.7 it now works and i can start the UI.
Thank you very much.
